const typeColors = {
Bug:'#ADBD21',
Dark:'#735A4A',
Dragon:'#7B63E7',
Electric:'#FFC631',
Fairy:'#EF70EF',
Fighting:'#A55239',
Fire:'#F75231',
Flying:'#9CADF7',
Ghost:'#6363B5',
Grass:'#7BCE52',
Ground:'#AE7A3B',
Ice:'#5ACEE7',
Normal:'#ADA594',
Poison:'#9141CB',
Psychic:'#EF4179',
Rock:'#BDA55A',
Steel:'#81A6BE',
Water:'#399CFF',
}
const possibleFilters = [
{categ:'Type', value:'Bug'},
{categ:'Type', value:'Dark'},
{categ:'Type', value:'Dragon'},
{categ:'Type', value:'Electric'},
{categ:'Type', value:'Fairy'},
{categ:'Type', value:'Fighting'},
{categ:'Type', value:'Fire'},
{categ:'Type', value:'Flying'},
{categ:'Type', value:'Ghost'},
{categ:'Type', value:'Grass'},
{categ:'Type', value:'Ground'},
{categ:'Type', value:'Ice'},
{categ:'Type', value:'Normal'},
{categ:'Type', value:'Poison'},
{categ:'Type', value:'Psychic'},
{categ:'Type', value:'Rock'},
{categ:'Type', value:'Steel'},
{categ:'Type', value:'Water'},
{categ:'Ability', value:'Overgrow'},
{categ:'Ability', value:'Chlorophyll'},
{categ:'Ability', value:'Grassy Surge'},
{categ:'Ability', value:'Thick Fat'},
{categ:'Ability', value:'Effect Spore'},
{categ:'Ability', value:'Blaze'},
{categ:'Ability', value:'Solar Power'},
{categ:'Ability', value:'Beast Boost'},
{categ:'Ability', value:'Tough Claws'},
{categ:'Ability', value:'Drought'},
{categ:'Ability', value:'Berserk'},
{categ:'Ability', value:'Torrent'},
{categ:'Ability', value:'Rain Dish'},
{categ:'Ability', value:'Sturdy'},
{categ:'Ability', value:'Mega Launcher'},
{categ:'Ability', value:'Shell Armor'},
{categ:'Ability', value:'Shield Dust'},
{categ:'Ability', value:'Run Away'},
{categ:'Ability', value:'Magician'},
{categ:'Ability', value:'Shed Skin'},
{categ:'Ability', value:'Compound Eyes'},
{categ:'Ability', value:'Tinted Lens'},
{categ:'Ability', value:'Swarm'},
{categ:'Ability', value:'Sniper'},
{categ:'Ability', value:'Adaptability'},
{categ:'Ability', value:'Keen Eye'},
{categ:'Ability', value:'Tangled Feet'},
{categ:'Ability', value:'Big Pecks'},
{categ:'Ability', value:'Sheer Force'},
{categ:'Ability', value:'No Guard'},
{categ:'Ability', value:'Guts'},
{categ:'Ability', value:'Hustle'},
{categ:'Ability', value:'Strong Jaw'},
{categ:'Ability', value:'Moxie'},
{categ:'Ability', value:'Intimidate'},
{categ:'Ability', value:'Unnerve'},
{categ:'Ability', value:'Regenerator'},
{categ:'Ability', value:'Static'},
{categ:'Ability', value:'Lightning Rod'},
{categ:'Ability', value:'Electric Surge'},
{categ:'Ability', value:'Sand Veil'},
{categ:'Ability', value:'Sand Rush'},
{categ:'Ability', value:'Poison Point'},
{categ:'Ability', value:'Rivalry'},
{categ:'Ability', value:'Flare Boost'},
{categ:'Ability', value:'Cute Charm'},
{categ:'Ability', value:'Magic Guard'},
{categ:'Ability', value:'Friend Guard'},
{categ:'Ability', value:'Analytic'},
{categ:'Ability', value:'Unaware'},
{categ:'Ability', value:'Flash Fire'},
{categ:'Ability', value:'Fur Coat'},
{categ:'Ability', value:'Competitive'},
{categ:'Ability', value:'Huge Power'},
{categ:'Ability', value:'Frisk'},
{categ:'Ability', value:'Inner Focus'},
{categ:'Ability', value:'Infiltrator'},
{categ:'Ability', value:'Triage'},
{categ:'Ability', value:'Stench'},
{categ:'Ability', value:'Dry Skin'},
{categ:'Ability', value:'Damp'},
{categ:'Ability', value:'Simple'},
{categ:'Ability', value:'Wonder Skin'},
{categ:'Ability', value:'Arena Trap'},
{categ:'Ability', value:'Sand Force'},
{categ:'Ability', value:'Pickup'},
{categ:'Ability', value:'Technician'},
{categ:'Ability', value:'Limber'},
{categ:'Ability', value:'Cloud Nine'},
{categ:'Ability', value:'Swift Swim'},
{categ:'Ability', value:'Vital Spirit'},
{categ:'Ability', value:'Anger Point'},
{categ:'Ability', value:'Defiant'},
{categ:'Ability', value:'Iron Fist'},
{categ:'Ability', value:'Justified'},
{categ:'Ability', value:'Fluffy'},
{categ:'Ability', value:'Water Absorb'},
{categ:'Ability', value:'Synchronize'},
{categ:'Ability', value:'Trace'},
{categ:'Ability', value:'Steadfast'},
{categ:'Ability', value:'Quick Feet'},
{categ:'Ability', value:'Gluttony'},
{categ:'Ability', value:'Flower Gift'},
{categ:'Ability', value:'Clear Body'},
{categ:'Ability', value:'Liquid Ooze'},
{categ:'Ability', value:'Toxic Chain'},
{categ:'Ability', value:'Rock Head'},
{categ:'Ability', value:'Flame Body'},
{categ:'Ability', value:'Oblivious'},
{categ:'Ability', value:'Own Tempo'},
{categ:'Ability', value:'Magnet Pull'},
{categ:'Ability', value:'Levitate'},
{categ:'Ability', value:'Early Bird'},
{categ:'Ability', value:'Parental Bond'},
{categ:'Ability', value:'Hydration'},
{categ:'Ability', value:'Ice Body'},
{categ:'Ability', value:'Water Bubble'},
{categ:'Ability', value:'Sticky Hold'},
{categ:'Ability', value:'Poison Touch'},
{categ:'Ability', value:'Skill Link'},
{categ:'Ability', value:'Overcoat'},
{categ:'Ability', value:'Ice Scales'},
{categ:'Ability', value:'Shadow Shield'},
{categ:'Ability', value:'Cursed Body'},
{categ:'Ability', value:'Shadow Tag'},
{categ:'Ability', value:'Weak Armor'},
{categ:'Ability', value:'Rocky Payload'},
{categ:'Ability', value:'Insomnia'},
{categ:'Ability', value:'Forewarn'},
{categ:'Ability', value:'Hyper Cutter'},
{categ:'Ability', value:'Unburden'},
{categ:'Ability', value:'Soundproof'},
{categ:'Ability', value:'Aftermath'},
{categ:'Ability', value:'Transistor'},
{categ:'Ability', value:'Harvest'},
{categ:'Ability', value:'Ripen'},
{categ:'Ability', value:'Battle Armor'},
{categ:'Ability', value:'Reckless'},
{categ:'Ability', value:'Cheek Pouch'},
{categ:'Ability', value:'Neutralizing Gas'},
{categ:'Ability', value:'Filter'},
{categ:'Ability', value:'Natural Cure'},
{categ:'Ability', value:'Serene Grace'},
{categ:'Ability', value:'Healer'},
{categ:'Ability', value:'Leaf Guard'},
{categ:'Ability', value:'Seed Sower'},
{categ:'Ability', value:'Scrappy'},
{categ:'Ability', value:'Dragons Maw'},
{categ:'Ability', value:'Water Veil'},
{categ:'Ability', value:'Multiscale'},
{categ:'Ability', value:'Illuminate'},
{categ:'Ability', value:'Prankster'},
{categ:'Ability', value:'Psychic Surge'},
{categ:'Ability', value:'Mold Breaker'},
{categ:'Ability', value:'Aerilate'},
{categ:'Ability', value:'Stamina'},
{categ:'Ability', value:'Rattled'},
{categ:'Ability', value:'Imposter'},
{categ:'Ability', value:'Anticipation'},
{categ:'Ability', value:'Protean'},
{categ:'Ability', value:'Volt Absorb'},
{categ:'Ability', value:'Download'},
{categ:'Ability', value:'Pressure'},
{categ:'Ability', value:'Orichalcum Pulse'},
{categ:'Ability', value:'Immunity'},
{categ:'Ability', value:'Snow Cloak'},
{categ:'Ability', value:'Snow Warning'},
{categ:'Ability', value:'Drizzle'},
{categ:'Ability', value:'Marvel Scale'},
{categ:'Ability', value:'Neuroforce'},
{categ:'Ability', value:'Super Luck'},
{categ:'Ability', value:'Pixilate'},
{categ:'Ability', value:'Magic Bounce'},
{categ:'Ability', value:'Plus'},
{categ:'Ability', value:'Electromorphosis'},
{categ:'Ability', value:'Sap Sipper'},
{categ:'Ability', value:'Misty Surge'},
{categ:'Ability', value:'Speed Boost'},
{categ:'Ability', value:'Comatose'},
{categ:'Ability', value:'Dark Aura'},
{categ:'Ability', value:'Beads Of Ruin'},
{categ:'Ability', value:'Telepathy'},
{categ:'Ability', value:'Iron Barbs'},
{categ:'Ability', value:'Toxic Boost'},
{categ:'Ability', value:'Toxic Debris'},
{categ:'Ability', value:'Light Metal'},
{categ:'Ability', value:'Contrary'},
{categ:'Ability', value:'Pickpocket'},
{categ:'Ability', value:'Honey Gather'},
{categ:'Ability', value:'Magma Armor'},
{categ:'Ability', value:'Desolate Land'},
{categ:'Ability', value:'Slush Rush'},
{categ:'Ability', value:'Storm Drain'},
{categ:'Ability', value:'Moody'},
{categ:'Ability', value:'Suction Cups'},
{categ:'Ability', value:'Sand Stream'},
{categ:'Ability', value:'Delta Stream'},
{categ:'Ability', value:'Sharpness'},
{categ:'Ability', value:'Wind Rider'},
{categ:'Ability', value:'Poison Heal'},
{categ:'Ability', value:'Truant'},
{categ:'Ability', value:'Stall'},
{categ:'Ability', value:'Wonder Guard'},
{categ:'Ability', value:'Punk Rock'},
{categ:'Ability', value:'Normalize'},
{categ:'Ability', value:'Heavy Metal'},
{categ:'Ability', value:'Earth Eater'},
{categ:'Ability', value:'Pure Power'},
{categ:'Ability', value:'Minds Eye'},
{categ:'Ability', value:'Minus'},
{categ:'Ability', value:'Power Spot'},
{categ:'Ability', value:'Rough Skin'},
{categ:'Ability', value:'Solid Rock'},
{categ:'Ability', value:'White Smoke'},
{categ:'Ability', value:'Well Baked Body'},
{categ:'Ability', value:'Forecast'},
{categ:'Ability', value:'Color Change'},
{categ:'Ability', value:'Refrigerate'},
{categ:'Ability', value:'Primordial Sea'},
{categ:'Ability', value:'Steely Spirit'},
{categ:'Ability', value:'Prism Armor'},
{categ:'Ability', value:'Turboblaze'},
{categ:'Ability', value:'Air Lock'},
{categ:'Ability', value:'Klutz'},
{categ:'Ability', value:'Heatproof'},
{categ:'Ability', value:'Mirror Armor'},
{categ:'Ability', value:'Vessel Of Ruin'},
{categ:'Ability', value:'Motor Drive'},
{categ:'Ability', value:'Hadron Engine'},
{categ:'Ability', value:'Slow Start'},
{categ:'Ability', value:'Bad Dreams'},
{categ:'Ability', value:'Multitype'},
{categ:'Ability', value:'Victory Star'},
{categ:'Ability', value:'Intrepid Sword'},
{categ:'Ability', value:'Opportunist'},
{categ:'Ability', value:'Supreme Overlord'},
{categ:'Ability', value:'Gorilla Tactics'},
{categ:'Ability', value:'Zen Mode'},
{categ:'Ability', value:'Mummy'},
{categ:'Ability', value:'Purifying Salt'},
{categ:'Ability', value:'Defeatist'},
{categ:'Ability', value:'Emergency Exit'},
{categ:'Ability', value:'Illusion'},
{categ:'Ability', value:'Quick Draw'},
{categ:'Ability', value:'Sword Of Ruin'},
{categ:'Ability', value:'Teravolt'},
{categ:'Ability', value:'Grim Neigh'},
{categ:'Ability', value:'Bulletproof'},
{categ:'Ability', value:'Dauntless Shield'},
{categ:'Ability', value:'Stakeout'},
{categ:'Ability', value:'Battle Bond'},
{categ:'Ability', value:'Gale Wings'},
{categ:'Ability', value:'Flower Veil'},
{categ:'Ability', value:'Symbiosis'},
{categ:'Ability', value:'Grass Pelt'},
{categ:'Ability', value:'Stance Change'},
{categ:'Ability', value:'Aroma Veil'},
{categ:'Ability', value:'Sweet Veil'},
{categ:'Ability', value:'Gooey'},
{categ:'Ability', value:'Fairy Aura'},
{categ:'Ability', value:'Soul Heart'},
{categ:'Ability', value:'Aura Break'},
{categ:'Ability', value:'Power Construct'},
{categ:'Ability', value:'Long Reach'},
{categ:'Ability', value:'Liquid Voice'},
{categ:'Ability', value:'Battery'},
{categ:'Ability', value:'Dancer'},
{categ:'Ability', value:'Schooling'},
{categ:'Ability', value:'Merciless'},
{categ:'Ability', value:'Cud Chew'},
{categ:'Ability', value:'Corrosion'},
{categ:'Ability', value:'Queenly Majesty'},
{categ:'Ability', value:'Receiver'},
{categ:'Ability', value:'Libero'},
{categ:'Ability', value:'Wimp Out'},
{categ:'Ability', value:'Water Compaction'},
{categ:'Ability', value:'Sand Spit'},
{categ:'Ability', value:'Innards Out'},
{categ:'Ability', value:'Rks System'},
{categ:'Ability', value:'Shields Down'},
{categ:'Ability', value:'Disguise'},
{categ:'Ability', value:'Dazzling'},
{categ:'Ability', value:'Steelworker'},
{categ:'Ability', value:'Full Metal Body'},
{categ:'Ability', value:'Cotton Down'},
{categ:'Ability', value:'Ball Fetch'},
{categ:'Ability', value:'Steam Engine'},
{categ:'Ability', value:'Gulp Missile'},
{categ:'Ability', value:'Propeller Tail'},
{categ:'Ability', value:'Perish Body'},
{categ:'Ability', value:'Screen Cleaner'},
{categ:'Ability', value:'Wandering Spirit'},
{categ:'Ability', value:'Tablets Of Ruin'},
{categ:'Ability', value:'Ice Face'},
{categ:'Ability', value:'Hunger Switch'},
{categ:'Ability', value:'Stalwart'},
{categ:'Ability', value:'Unseen Fist'},
{categ:'Ability', value:'Chilling Neigh'},
{categ:'Ability', value:'As One Glastrier'},
{categ:'Ability', value:'As One Spectrier'},
{categ:'Ability', value:'Lingering Aroma'},
{categ:'Ability', value:'Wind Power'},
{categ:'Ability', value:'Guard Dog'},
{categ:'Ability', value:'Mycelium Might'},
{categ:'Ability', value:'Anger Shell'},
{categ:'Ability', value:'Zero To Hero'},
{categ:'Ability', value:'Costar'},
{categ:'Ability', value:'Commander'},
{categ:'Ability', value:'Armor Tail'},
{categ:'Ability', value:'Protosynthesis'},
{categ:'Ability', value:'Quark Drive'},
{categ:'Ability', value:'Thermal Exchange'},
{categ:'Ability', value:'Good As Gold'},
{categ:'Ability', value:'Supersweet Syrup'},
{categ:'Ability', value:'Hospitality'},
{categ:'Ability', value:'Embody Aspect Teal'},
{categ:'Ability', value:'Embody Aspect Wellspring'},
{categ:'Ability', value:'Embody Aspect Hearthflame'},
{categ:'Ability', value:'Embody Aspect Cornerstone'},
{categ:'Ability', value:'Tera Shift'},
{categ:'Ability', value:'Tera Shell'},
{categ:'Ability', value:'Teraform Zero'},
{categ:'Ability', value:'Poison Puppeteer'},
{categ:'Ability', value:'Surge Surfer'},
{categ:'Ability', value:'Tangling Hair'},
{categ:'Ability', value:'Galvanize'},
{categ:'Ability', value:'Power Of Alchemy'},
{categ:'Ability', value:'Pastel Veil'},
{categ:'Ability', value:'Curious Medicine'},
{categ:'Ability', value:'Mimicry'},
{categ:'Move', value:'Tackle'},
{categ:'Move', value:'Growl'},
{categ:'Move', value:'Vine Whip'},
{categ:'Move', value:'Growth'},
{categ:'Move', value:'Leech Seed'},
{categ:'Move', value:'Razor Leaf'},
{categ:'Move', value:'Poison Powder'},
{categ:'Move', value:'Sleep Powder'},
{categ:'Move', value:'Seed Bomb'},
{categ:'Move', value:'Take Down'},
{categ:'Move', value:'Sweet Scent'},
{categ:'Move', value:'Synthesis'},
{categ:'Move', value:'Worry Seed'},
{categ:'Move', value:'Power Whip'},
{categ:'Move', value:'Solar Beam'},
{categ:'Move', value:'Petal Blizzard'},
{categ:'Move', value:'Petal Dance'},
{categ:'Move', value:'Scratch'},
{categ:'Move', value:'Ember'},
{categ:'Move', value:'Smokescreen'},
{categ:'Move', value:'Dragon Breath'},
{categ:'Move', value:'Fire Fang'},
{categ:'Move', value:'Slash'},
{categ:'Move', value:'Flamethrower'},
{categ:'Move', value:'Scary Face'},
{categ:'Move', value:'Fire Spin'},
{categ:'Move', value:'Inferno'},
{categ:'Move', value:'Flare Blitz'},
{categ:'Move', value:'Air Slash'},
{categ:'Move', value:'Heat Wave'},
{categ:'Move', value:'Dragon Claw'},
{categ:'Move', value:'Tail Whip'},
{categ:'Move', value:'Water Gun'},
{categ:'Move', value:'Withdraw'},
{categ:'Move', value:'Rapid Spin'},
{categ:'Move', value:'Bite'},
{categ:'Move', value:'Water Pulse'},
{categ:'Move', value:'Protect'},
{categ:'Move', value:'Rain Dance'},
{categ:'Move', value:'Aqua Tail'},
{categ:'Move', value:'Shell Smash'},
{categ:'Move', value:'Iron Defense'},
{categ:'Move', value:'Hydro Pump'},
{categ:'Move', value:'Wave Crash'},
{categ:'Move', value:'Flash Cannon'},
{categ:'Move', value:'String Shot'},
{categ:'Move', value:'Bug Bite'},
{categ:'Move', value:'Harden'},
{categ:'Move', value:'Gust'},
{categ:'Move', value:'Supersonic'},
{categ:'Move', value:'Confusion'},
{categ:'Move', value:'Stun Spore'},
{categ:'Move', value:'Psybeam'},
{categ:'Move', value:'Whirlwind'},
{categ:'Move', value:'Safeguard'},
{categ:'Move', value:'Bug Buzz'},
{categ:'Move', value:'Tailwind'},
{categ:'Move', value:'Rage Powder'},
{categ:'Move', value:'Quiver Dance'},
{categ:'Move', value:'Poison Sting'},
{categ:'Move', value:'Twineedle'},
{categ:'Move', value:'Fury Attack'},
{categ:'Move', value:'Fury Cutter'},
{categ:'Move', value:'Rage'},
{categ:'Move', value:'Pursuit'},
{categ:'Move', value:'Focus Energy'},
{categ:'Move', value:'Venoshock'},
{categ:'Move', value:'Assurance'},
{categ:'Move', value:'Toxic Spikes'},
{categ:'Move', value:'Pin Missile'},
{categ:'Move', value:'Poison Jab'},
{categ:'Move', value:'Agility'},
{categ:'Move', value:'Endeavor'},
{categ:'Move', value:'Fell Stinger'},
{categ:'Move', value:'Sand Attack'},
{categ:'Move', value:'Quick Attack'},
{categ:'Move', value:'Twister'},
{categ:'Move', value:'Feather Dance'},
{categ:'Move', value:'Wing Attack'},
{categ:'Move', value:'Roost'},
{categ:'Move', value:'Aerial Ace'},
{categ:'Move', value:'Hurricane'},
{categ:'Move', value:'Laser Focus'},
{categ:'Move', value:'Crunch'},
{categ:'Move', value:'Sucker Punch'},
{categ:'Move', value:'Super Fang'},
{categ:'Move', value:'Double Edge'},
{categ:'Move', value:'Swords Dance'},
{categ:'Move', value:'Peck'},
{categ:'Move', value:'Leer'},
{categ:'Move', value:'Drill Peck'},
{categ:'Move', value:'Pluck'},
{categ:'Move', value:'Drill Run'},
{categ:'Move', value:'Wrap'},
{categ:'Move', value:'Glare'},
{categ:'Move', value:'Screech'},
{categ:'Move', value:'Acid'},
{categ:'Move', value:'Swallow'},
{categ:'Move', value:'Stockpile'},
{categ:'Move', value:'Spit Up'},
{categ:'Move', value:'Acid Spray'},
{categ:'Move', value:'Sludge Bomb'},
{categ:'Move', value:'Gastro Acid'},
{categ:'Move', value:'Belch'},
{categ:'Move', value:'Haze'},
{categ:'Move', value:'Coil'},
{categ:'Move', value:'Gunk Shot'},
{categ:'Move', value:'Thunder Fang'},
{categ:'Move', value:'Ice Fang'},
{categ:'Move', value:'Thunder Shock'},
{categ:'Move', value:'Sweet Kiss'},
{categ:'Move', value:'Charm'},
{categ:'Move', value:'Nasty Plot'},
{categ:'Move', value:'Play Nice'},
{categ:'Move', value:'Nuzzle'},
{categ:'Move', value:'Thunder Wave'},
{categ:'Move', value:'Double Team'},
{categ:'Move', value:'Electro Ball'},
{categ:'Move', value:'Feint'},
{categ:'Move', value:'Spark'},
{categ:'Move', value:'Iron Tail'},
{categ:'Move', value:'Discharge'},
{categ:'Move', value:'Thunderbolt'},
{categ:'Move', value:'Light Screen'},
{categ:'Move', value:'Thunder'},
{categ:'Move', value:'Pika Papow'},
{categ:'Move', value:'Zippy Zap'},
{categ:'Move', value:'Thunder Punch'},
{categ:'Move', value:'Defense Curl'},
{categ:'Move', value:'Rollout'},
{categ:'Move', value:'Bulldoze'},
{categ:'Move', value:'Swift'},
{categ:'Move', value:'Fury Swipes'},
{categ:'Move', value:'Dig'},
{categ:'Move', value:'Gyro Ball'},
{categ:'Move', value:'Sandstorm'},
{categ:'Move', value:'Earthquake'},
{categ:'Move', value:'Crush Claw'},
{categ:'Move', value:'Sand Tomb'},
{categ:'Move', value:'Double Kick'},
{categ:'Move', value:'Helping Hand'},
{categ:'Move', value:'Toxic'},
{categ:'Move', value:'Flatter'},
{categ:'Move', value:'Earth Power'},
{categ:'Move', value:'Superpower'},
{categ:'Move', value:'Sludge Wave'},
{categ:'Move', value:'Horn Attack'},
{categ:'Move', value:'Megahorn'},
{categ:'Move', value:'Pound'},
{categ:'Move', value:'Sing'},
{categ:'Move', value:'Splash'},
{categ:'Move', value:'Copycat'},
{categ:'Move', value:'Disarming Voice'},
{categ:'Move', value:'Spotlight'},
{categ:'Move', value:'Stored Power'},
{categ:'Move', value:'Encore'},
{categ:'Move', value:'After You'},
{categ:'Move', value:'Life Dew'},
{categ:'Move', value:'Metronome'},
{categ:'Move', value:'Moonlight'},
{categ:'Move', value:'Gravity'},
{categ:'Move', value:'Meteor Mash'},
{categ:'Move', value:'Follow Me'},
{categ:'Move', value:'Cosmic Power'},
{categ:'Move', value:'Moonblast'},
{categ:'Move', value:'Healing Wish'},
{categ:'Move', value:'Disable'},
{categ:'Move', value:'Spite'},
{categ:'Move', value:'Incinerate'},
{categ:'Move', value:'Confuse Ray'},
{categ:'Move', value:'Will O Wisp'},
{categ:'Move', value:'Extrasensory'},
{categ:'Move', value:'Imprison'},
{categ:'Move', value:'Fire Blast'},
{categ:'Move', value:'Echoed Voice'},
{categ:'Move', value:'Covet'},
{categ:'Move', value:'Round'},
{categ:'Move', value:'Rest'},
{categ:'Move', value:'Body Slam'},
{categ:'Move', value:'Mimic'},
{categ:'Move', value:'Hyper Voice'},
{categ:'Move', value:'Play Rough'},
{categ:'Move', value:'Absorb'},
{categ:'Move', value:'Astonish'},
{categ:'Move', value:'Mean Look'},
{categ:'Move', value:'Poison Fang'},
{categ:'Move', value:'Quick Guard'},
{categ:'Move', value:'Air Cutter'},
{categ:'Move', value:'Leech Life'},
{categ:'Move', value:'Mega Drain'},
{categ:'Move', value:'Giga Drain'},
{categ:'Move', value:'Grassy Terrain'},
{categ:'Move', value:'Aromatherapy'},
{categ:'Move', value:'Spore'},
{categ:'Move', value:'X Scissor'},
{categ:'Move', value:'Cross Poison'},
{categ:'Move', value:'Zen Headbutt'},
{categ:'Move', value:'Psychic'},
{categ:'Move', value:'Silver Wind'},
{categ:'Move', value:'Mud Slap'},
{categ:'Move', value:'Fissure'},
{categ:'Move', value:'Tri Attack'},
{categ:'Move', value:'Night Slash'},
{categ:'Move', value:'Rototiller'},
{categ:'Move', value:'Fake Out'},
{categ:'Move', value:'Pay Day'},
{categ:'Move', value:'Taunt'},
{categ:'Move', value:'Power Gem'},
{categ:'Move', value:'Switcheroo'},
{categ:'Move', value:'Water Sport'},
{categ:'Move', value:'Soak'},
{categ:'Move', value:'Psych Up'},
{categ:'Move', value:'Amnesia'},
{categ:'Move', value:'Wonder Room'},
{categ:'Move', value:'Aqua Jet'},
{categ:'Move', value:'Me First'},
{categ:'Move', value:'Low Kick'},
{categ:'Move', value:'Seismic Toss'},
{categ:'Move', value:'Swagger'},
{categ:'Move', value:'Cross Chop'},
{categ:'Move', value:'Thrash'},
{categ:'Move', value:'Close Combat'},
{categ:'Move', value:'Stomping Tantrum'},
{categ:'Move', value:'Outrage'},
{categ:'Move', value:'Final Gambit'},
{categ:'Move', value:'Fling'},
{categ:'Move', value:'Rage Fist'},
{categ:'Move', value:'Howl'},
{categ:'Move', value:'Flame Wheel'},
{categ:'Move', value:'Retaliate'},
{categ:'Move', value:'Roar'},
{categ:'Move', value:'Reversal'},
{categ:'Move', value:'Extreme Speed'},
{categ:'Move', value:'Odor Sleuth'},
{categ:'Move', value:'Hypnosis'},
{categ:'Move', value:'Mud Shot'},
{categ:'Move', value:'Bubble Beam'},
{categ:'Move', value:'Belly Drum'},
{categ:'Move', value:'Dynamic Punch'},
{categ:'Move', value:'Circle Throw'},
{categ:'Move', value:'Teleport'},
{categ:'Move', value:'Kinesis'},
{categ:'Move', value:'Reflect'},
{categ:'Move', value:'Ally Switch'},
{categ:'Move', value:'Psycho Cut'},
{categ:'Move', value:'Recover'},
{categ:'Move', value:'Psyshock'},
{categ:'Move', value:'Role Play'},
{categ:'Move', value:'Future Sight'},
{categ:'Move', value:'Calm Mind'},
{categ:'Move', value:'Revenge'},
{categ:'Move', value:'Low Sweep'},
{categ:'Move', value:'Knock Off'},
{categ:'Move', value:'Vital Throw'},
{categ:'Move', value:'Strength'},
{categ:'Move', value:'Dual Chop'},
{categ:'Move', value:'Bulk Up'},
{categ:'Move', value:'Karate Chop'},
{categ:'Move', value:'Wide Guard'},
{categ:'Move', value:'Slam'},
{categ:'Move', value:'Leaf Storm'},
{categ:'Move', value:'Leaf Blade'},
{categ:'Move', value:'Hex'},
{categ:'Move', value:'Acid Armor'},
{categ:'Move', value:'Surf'},
{categ:'Move', value:'Reflect Type'},
{categ:'Move', value:'Wring Out'},
{categ:'Move', value:'Rock Polish'},
{categ:'Move', value:'Rock Throw'},
{categ:'Move', value:'Smack Down'},
{categ:'Move', value:'Self Destruct'},
{categ:'Move', value:'Stealth Rock'},
{categ:'Move', value:'Rock Blast'},
{categ:'Move', value:'Explosion'},
{categ:'Move', value:'Stone Edge'},
{categ:'Move', value:'Heavy Slam'},
{categ:'Move', value:'Flame Charge'},
{categ:'Move', value:'Stomp'},
{categ:'Move', value:'Smart Strike'},
{categ:'Move', value:'Curse'},
{categ:'Move', value:'Yawn'},
{categ:'Move', value:'Headbutt'},
{categ:'Move', value:'Slack Off'},
{categ:'Move', value:'Heal Pulse'},
{categ:'Move', value:'Magnet Rise'},
{categ:'Move', value:'Metal Sound'},
{categ:'Move', value:'Lock On'},
{categ:'Move', value:'Zap Cannon'},
{categ:'Move', value:'Electric Terrain'},
{categ:'Move', value:'Cut'},
{categ:'Move', value:'False Swipe'},
{categ:'Move', value:'Brave Bird'},
{categ:'Move', value:'Double Hit'},
{categ:'Move', value:'Uproar'},
{categ:'Move', value:'Acupressure'},
{categ:'Move', value:'Icy Wind'},
{categ:'Move', value:'Ice Shard'},
{categ:'Move', value:'Aqua Ring'},
{categ:'Move', value:'Aurora Beam'},
{categ:'Move', value:'Brine'},
{categ:'Move', value:'Dive'},
{categ:'Move', value:'Ice Beam'},
{categ:'Move', value:'Snowscape'},
{categ:'Move', value:'Sheer Cold'},
{categ:'Move', value:'Signal Beam'},
{categ:'Move', value:'Poison Gas'},
{categ:'Move', value:'Sludge'},
{categ:'Move', value:'Minimize'},
{categ:'Move', value:'Memento'},
{categ:'Move', value:'Whirlpool'},
{categ:'Move', value:'Razor Shell'},
{categ:'Move', value:'Icicle Spear'},
{categ:'Move', value:'Spikes'},
{categ:'Move', value:'Icicle Crash'},
{categ:'Move', value:'Lick'},
{categ:'Move', value:'Payback'},
{categ:'Move', value:'Night Shade'},
{categ:'Move', value:'Dark Pulse'},
{categ:'Move', value:'Shadow Ball'},
{categ:'Move', value:'Destiny Bond'},
{categ:'Move', value:'Dream Eater'},
{categ:'Move', value:'Shadow Punch'},
{categ:'Move', value:'Perish Song'},
{categ:'Move', value:'Bind'},
{categ:'Move', value:'Mud Sport'},
{categ:'Move', value:'Rock Slide'},
{categ:'Move', value:'Nightmare'},
{categ:'Move', value:'Metal Claw'},
{categ:'Move', value:'Flail'},
{categ:'Move', value:'Crabhammer'},
{categ:'Move', value:'Guillotine'},
{categ:'Move', value:'Hammer Arm'},
{categ:'Move', value:'Charge'},
{categ:'Move', value:'Eerie Impulse'},
{categ:'Move', value:'Charge Beam'},
{categ:'Move', value:'Mirror Coat'},
{categ:'Move', value:'Magnetic Flux'},
{categ:'Move', value:'Barrage'},
{categ:'Move', value:'Bullet Seed'},
{categ:'Move', value:'Wood Hammer'},
{categ:'Move', value:'Bone Rush'},
{categ:'Move', value:'Bonemerang'},
{categ:'Move', value:'Bone Club'},
{categ:'Move', value:'Brick Break'},
{categ:'Move', value:'Jump Kick'},
{categ:'Move', value:'Rolling Kick'},
{categ:'Move', value:'Mach Punch'},
{categ:'Move', value:'Endure'},
{categ:'Move', value:'Blaze Kick'},
{categ:'Move', value:'Mega Kick'},
{categ:'Move', value:'High Jump Kick'},
{categ:'Move', value:'Axe Kick'},
{categ:'Move', value:'Drain Punch'},
{categ:'Move', value:'Comet Punch'},
{categ:'Move', value:'Vacuum Wave'},
{categ:'Move', value:'Detect'},
{categ:'Move', value:'Bullet Punch'},
{categ:'Move', value:'Ice Punch'},
{categ:'Move', value:'Fire Punch'},
{categ:'Move', value:'Mega Punch'},
{categ:'Move', value:'Counter'},
{categ:'Move', value:'Focus Punch'},
{categ:'Move', value:'Smog'},
{categ:'Move', value:'Clear Smog'},
{categ:'Move', value:'Horn Drill'},
{categ:'Move', value:'Soft Boiled'},
{categ:'Move', value:'Last Resort'},
{categ:'Move', value:'Constrict'},
{categ:'Move', value:'Ancient Power'},
{categ:'Move', value:'Tickle'},
{categ:'Move', value:'Ingrain'},
{categ:'Move', value:'Dragon Pulse'},
{categ:'Move', value:'Dragon Dance'},
{categ:'Move', value:'Waterfall'},
{categ:'Move', value:'Baton Pass'},
{categ:'Move', value:'Power Swap'},
{categ:'Move', value:'Guard Swap'},
{categ:'Move', value:'Barrier'},
{categ:'Move', value:'Recycle'},
{categ:'Move', value:'Dazzling Gleam'},
{categ:'Move', value:'Teeter Dance'},
{categ:'Move', value:'Steel Wing'},
{categ:'Move', value:'Powder Snow'},
{categ:'Move', value:'Fake Tears'},
{categ:'Move', value:'Lovely Kiss'},
{categ:'Move', value:'Blizzard'},
{categ:'Move', value:'Shock Wave'},
{categ:'Move', value:'Giga Impact'},
{categ:'Move', value:'Lava Plume'},
{categ:'Move', value:'Sunny Day'},
{categ:'Move', value:'Hyper Beam'},
{categ:'Move', value:'Vise Grip'},
{categ:'Move', value:'Storm Throw'},
{categ:'Move', value:'Submission'},
{categ:'Move', value:'Work Up'},
{categ:'Move', value:'Raging Bull'},
{categ:'Move', value:'Mist'},
{categ:'Move', value:'Transform'},
{categ:'Move', value:'Baby Doll Eyes'},
{categ:'Move', value:'Veevee Volley'},
{categ:'Move', value:'Bouncy Bubble'},
{categ:'Move', value:'Muddy Water'},
{categ:'Move', value:'Buzzy Buzz'},
{categ:'Move', value:'Sizzly Slide'},
{categ:'Move', value:'Conversion'},
{categ:'Move', value:'Conversion 2'},
{categ:'Move', value:'Magic Coat'},
{categ:'Move', value:'Spike Cannon'},
{categ:'Move', value:'Liquidation'},
{categ:'Move', value:'Iron Head'},
{categ:'Move', value:'Block'},
{categ:'Move', value:'Snore'},
{categ:'Move', value:'Sleep Talk'},
{categ:'Move', value:'High Horsepower'},
{categ:'Move', value:'Freeze Dry'},
{categ:'Move', value:'Overheat'},
{categ:'Move', value:'Sky Attack'},
{categ:'Move', value:'Dragon Tail'},
{categ:'Move', value:'Dragon Rush'},
{categ:'Move', value:'Aura Sphere'},
{categ:'Move', value:'Psystrike'},
{categ:'Move', value:'Magical Leaf'},
{categ:'Move', value:'Eruption'},
{categ:'Move', value:'Defog'},
{categ:'Move', value:'Struggle Bug'},
{categ:'Move', value:'Infestation'},
{categ:'Move', value:'Shadow Sneak'},
{categ:'Move', value:'Sticky Web'},
{categ:'Move', value:'Toxic Thread'},
{categ:'Move', value:'Wish'},
{categ:'Move', value:'Fairy Wind'},
{categ:'Move', value:'Psycho Shift'},
{categ:'Move', value:'Cotton Spore'},
{categ:'Move', value:'Cotton Guard'},
{categ:'Move', value:'Ion Deluge'},
{categ:'Move', value:'Bounce'},
{categ:'Move', value:'Rock Tomb'},
{categ:'Move', value:'Tearful Look'},
{categ:'Move', value:'Head Smash'},
{categ:'Move', value:'Acrobatics'},
{categ:'Move', value:'U Turn'},
{categ:'Move', value:'Glitzy Glow'},
{categ:'Move', value:'Morning Sun'},
{categ:'Move', value:'Baddy Bad'},
{categ:'Move', value:'Snarl'},
{categ:'Move', value:'Foul Play'},
{categ:'Move', value:'Torment'},
{categ:'Move', value:'Quash'},
{categ:'Move', value:'Chilly Reception'},
{categ:'Move', value:'Psywave'},
{categ:'Move', value:'Pain Split'},
{categ:'Move', value:'Hidden Power'},
{categ:'Move', value:'Twin Beam'},
{categ:'Move', value:'Mirror Shot'},
{categ:'Move', value:'Hyper Drill'},
{categ:'Move', value:'Poison Tail'},
{categ:'Move', value:'Autotomize'},
{categ:'Move', value:'Bide'},
{categ:'Move', value:'Guard Split'},
{categ:'Move', value:'Power Split'},
{categ:'Move', value:'Power Trick'},
{categ:'Move', value:'Arm Thrust'},
{categ:'Move', value:'Throat Chop'},
{categ:'Move', value:'Hone Claws'},
{categ:'Move', value:'Beat Up'},
{categ:'Move', value:'Octazooka'},
{categ:'Move', value:'Present'},
{categ:'Move', value:'Comeuppance'},
{categ:'Move', value:'Psyshield Bash'},
{categ:'Move', value:'Sketch'},
{categ:'Move', value:'Triple Kick'},
{categ:'Move', value:'Heal Bell'},
{categ:'Move', value:'Milk Drink'},
{categ:'Move', value:'Sacred Fire'},
{categ:'Move', value:'Weather Ball'},
{categ:'Move', value:'Aeroblast'},
{categ:'Move', value:'Heal Block'},
{categ:'Move', value:'Leafage'},
{categ:'Move', value:'Energy Ball'},
{categ:'Move', value:'Shed Tail'},
{categ:'Move', value:'Rock Smash'},
{categ:'Move', value:'Thief'},
{categ:'Move', value:'Attract'},
{categ:'Move', value:'Draining Kiss'},
{categ:'Move', value:'Misty Terrain'},
{categ:'Move', value:'Mystical Fire'},
{categ:'Move', value:'Ominous Wind'},
{categ:'Move', value:'Force Palm'},
{categ:'Move', value:'Mind Reader'},
{categ:'Move', value:'Shadow Claw'},
{categ:'Move', value:'Grudge'},
{categ:'Move', value:'Phantom Force'},
{categ:'Move', value:'Boomburst'},
{categ:'Move', value:'Headlong Rush'},
{categ:'Move', value:'Facade'},
{categ:'Move', value:'Metal Burst'},
{categ:'Move', value:'Wild Charge'},
{categ:'Move', value:'Entrainment'},
{categ:'Move', value:'Flash'},
{categ:'Move', value:'Tail Glow'},
{categ:'Move', value:'Water Spout'},
{categ:'Move', value:'Noble Roar'},
{categ:'Move', value:'Dizzy Punch'},
{categ:'Move', value:'Feint Attack'},
{categ:'Move', value:'Power Trip'},
{categ:'Move', value:'Spiky Shield'},
{categ:'Move', value:'Magic Room'},
{categ:'Move', value:'Hail'},
{categ:'Move', value:'Substitute'},
{categ:'Move', value:'Trick'},
{categ:'Move', value:'Synchronoise'},
{categ:'Move', value:'Frost Breath'},
{categ:'Move', value:'Ice Ball'},
{categ:'Move', value:'Clamp'},
{categ:'Move', value:'Fly'},
{categ:'Move', value:'Dual Wingbeat'},
{categ:'Move', value:'Mist Ball'},
{categ:'Move', value:'Luster Purge'},
{categ:'Move', value:'Simple Beam'},
{categ:'Move', value:'Origin Pulse'},
{categ:'Move', value:'Precipice Blades'},
{categ:'Move', value:'Dragon Ascent'},
{categ:'Move', value:'Doom Desire'},
{categ:'Move', value:'Skill Swap'},
{categ:'Move', value:'Psycho Boost'},
{categ:'Move', value:'Raging Fury'},
{categ:'Move', value:'Hyper Fang'},
{categ:'Move', value:'Volt Switch'},
{categ:'Move', value:'Venom Drench'},
{categ:'Move', value:'Chip Away'},
{categ:'Move', value:'Lunge'},
{categ:'Move', value:'Aromatic Mist'},
{categ:'Move', value:'Attack Order'},
{categ:'Move', value:'Defend Order'},
{categ:'Move', value:'Heal Order'},
{categ:'Move', value:'Flower Shield'},
{categ:'Move', value:'Strength Sap'},
{categ:'Move', value:'Frustration'},
{categ:'Move', value:'Return'},
{categ:'Move', value:'Lucky Chant'},
{categ:'Move', value:'Chatter'},
{categ:'Move', value:'Confide'},
{categ:'Move', value:'Mirror Move'},
{categ:'Move', value:'Grass Knot'},
{categ:'Move', value:'Leaf Tornado'},
{categ:'Move', value:'Aurora Veil'},
{categ:'Move', value:'Embargo'},
{categ:'Move', value:'Rock Wrecker'},
{categ:'Move', value:'Sappy Seed'},
{categ:'Move', value:'Freezy Frost'},
{categ:'Move', value:'Trick Room'},
{categ:'Move', value:'Sacred Sword'},
{categ:'Move', value:'Aqua Cutter'},
{categ:'Move', value:'Expanding Force'},
{categ:'Move', value:'Mystical Power'},
{categ:'Move', value:'Roar Of Time'},
{categ:'Move', value:'Spacial Rend'},
{categ:'Move', value:'Magma Storm'},
{categ:'Move', value:'Foresight'},
{categ:'Move', value:'Body Press'},
{categ:'Move', value:'Crush Grip'},
{categ:'Move', value:'Shadow Force'},
{categ:'Move', value:'Lunar Dance'},
{categ:'Move', value:'Lunar Blessing'},
{categ:'Move', value:'Take Heart'},
{categ:'Move', value:'Heart Swap'},
{categ:'Move', value:'Dark Void'},
{categ:'Move', value:'Natural Gift'},
{categ:'Move', value:'Seed Flare'},
{categ:'Move', value:'Punishment'},
{categ:'Move', value:'Judgment'},
{categ:'Move', value:'V Create'},
{categ:'Move', value:'Searing Shot'},
{categ:'Move', value:'Heat Crash'},
{categ:'Move', value:'Assist'},
{categ:'Move', value:'Flame Burst'},
{categ:'Move', value:'Scald'},
{categ:'Move', value:'Psychic Terrain'},
{categ:'Move', value:'Bubble'},
{categ:'Move', value:'Mat Block'},
{categ:'Move', value:'Grass Whistle'},
{categ:'Move', value:'Crafty Shield'},
{categ:'Move', value:'Night Daze'},
{categ:'Move', value:'Tail Slap'},
{categ:'Move', value:'Snatch'},
{categ:'Move', value:'Avalanche'},
{categ:'Move', value:'Camouflage'},
{categ:'Move', value:'Horn Leech'},
{categ:'Move', value:'Spider Web'},
{categ:'Move', value:'Electroweb'},
{categ:'Move', value:'Rock Climb'},
{categ:'Move', value:'Gear Grind'},
{categ:'Move', value:'Shift Gear'},
{categ:'Move', value:'Gear Up'},
{categ:'Move', value:'Breaking Swipe'},
{categ:'Move', value:'Water Shuriken'},
{categ:'Move', value:'Head Charge'},
{categ:'Move', value:'Fire Lash'},
{categ:'Move', value:'Fiery Dance'},
{categ:'Move', value:'Bleakwind Storm'},
{categ:'Move', value:'Wildbolt Storm'},
{categ:'Move', value:'Fusion Flare'},
{categ:'Move', value:'Blue Flare'},
{categ:'Move', value:'Fusion Bolt'},
{categ:'Move', value:'Bolt Strike'},
{categ:'Move', value:'Sandsear Storm'},
{categ:'Move', value:'Glaciate'},
{categ:'Move', value:'Secret Sword'},
{categ:'Move', value:'Relic Song'},
{categ:'Move', value:'Techno Blast'},
{categ:'Move', value:'Needle Arm'},
{categ:'Move', value:'Powder'},
{categ:'Move', value:'Parting Shot'},
{categ:'Move', value:'Kings Shield'},
{categ:'Move', value:'Topsy Turvy'},
{categ:'Move', value:'Skull Bash'},
{categ:'Move', value:'Parabolic Charge'},
{categ:'Move', value:'Electrify'},
{categ:'Move', value:'Razor Wind'},
{categ:'Move', value:'Nature Power'},
{categ:'Move', value:'Sparkly Swirl'},
{categ:'Move', value:'Flying Press'},
{categ:'Move', value:'Fairy Lock'},
{categ:'Move', value:'Branch Poke'},
{categ:'Move', value:'Forests Curse'},
{categ:'Move', value:'Trick Or Treat'},
{categ:'Move', value:'Geomancy'},
{categ:'Move', value:'Oblivion Wing'},
{categ:'Move', value:'Focus Blast'},
{categ:'Move', value:'Thousand Arrows'},
{categ:'Move', value:'Thousand Waves'},
{categ:'Move', value:'Core Enforcer'},
{categ:'Move', value:'Lands Wrath'},
{categ:'Move', value:'Diamond Storm'},
{categ:'Move', value:'Hyperspace Hole'},
{categ:'Move', value:'Steam Eruption'},
{categ:'Move', value:'Spirit Shackle'},
{categ:'Move', value:'Darkest Lariat'},
{categ:'Move', value:'Sparkling Aria'},
{categ:'Move', value:'Beak Blast'},
{categ:'Move', value:'Ice Hammer'},
{categ:'Move', value:'Revelation Dance'},
{categ:'Move', value:'Pollen Puff'},
{categ:'Move', value:'Accelerock'},
{categ:'Move', value:'Baneful Bunker'},
{categ:'Move', value:'Solar Blade'},
{categ:'Move', value:'Captivate'},
{categ:'Move', value:'Brutal Swing'},
{categ:'Move', value:'Trop Kick'},
{categ:'Move', value:'Floral Healing'},
{categ:'Move', value:'Instruct'},
{categ:'Move', value:'First Impression'},
{categ:'Move', value:'Shore Up'},
{categ:'Move', value:'Purify'},
{categ:'Move', value:'Multi Attack'},
{categ:'Move', value:'Shell Trap'},
{categ:'Move', value:'Zing Zap'},
{categ:'Move', value:'Psychic Fangs'},
{categ:'Move', value:'Anchor Shot'},
{categ:'Move', value:'Sky Uppercut'},
{categ:'Move', value:'Clanging Scales'},
{categ:'Move', value:'Clangorous Soul'},
{categ:'Move', value:'Natures Madness'},
{categ:'Move', value:'Sunsteel Strike'},
{categ:'Move', value:'Wake Up Slap'},
{categ:'Move', value:'Moongeist Beam'},
{categ:'Move', value:'Power Up Punch'},
{categ:'Move', value:'Speed Swap'},
{categ:'Move', value:'Photon Geyser'},
{categ:'Move', value:'Prismatic Laser'},
{categ:'Move', value:'Fleur Cannon'},
{categ:'Move', value:'Spectral Thief'},
{categ:'Move', value:'Mind Blown'},
{categ:'Move', value:'Plasma Fists'},
{categ:'Move', value:'Double Iron Bash'},
{categ:'Move', value:'Drum Beating'},
{categ:'Move', value:'Pyro Ball'},
{categ:'Move', value:'Court Change'},
{categ:'Move', value:'Snipe Shot'},
{categ:'Move', value:'Stuff Cheeks'},
{categ:'Move', value:'Jaw Lock'},
{categ:'Move', value:'Tar Shot'},
{categ:'Move', value:'Grav Apple'},
{categ:'Move', value:'Apple Acid'},
{categ:'Move', value:'Overdrive'},
{categ:'Move', value:'Burn Up'},
{categ:'Move', value:'Octolock'},
{categ:'Move', value:'Teatime'},
{categ:'Move', value:'Magic Powder'},
{categ:'Move', value:'False Surrender'},
{categ:'Move', value:'Spirit Break'},
{categ:'Move', value:'Obstruct'},
{categ:'Move', value:'Meteor Assault'},
{categ:'Move', value:'Decorate'},
{categ:'Move', value:'No Retreat'},
{categ:'Move', value:'Aura Wheel'},
{categ:'Move', value:'Bolt Beak'},
{categ:'Move', value:'Fishious Rend'},
{categ:'Move', value:'Dragon Darts'},
{categ:'Move', value:'Dynamax Cannon'},
{categ:'Move', value:'Wicked Blow'},
{categ:'Move', value:'Jungle Healing'},
{categ:'Move', value:'Thunder Cage'},
{categ:'Move', value:'Dragon Energy'},
{categ:'Move', value:'Stone Axe'},
{categ:'Move', value:'Dire Claw'},
{categ:'Move', value:'Barb Barrage'},
{categ:'Move', value:'Springtide Storm'},
{categ:'Move', value:'Flower Trick'},
{categ:'Move', value:'Torch Song'},
{categ:'Move', value:'Aqua Step'},
{categ:'Move', value:'Skitter Smack'},
{categ:'Move', value:'Silk Trap'},
{categ:'Move', value:'Revival Blessing'},
{categ:'Move', value:'Double Shock'},
{categ:'Move', value:'Population Bomb'},
{categ:'Move', value:'Tidy Up'},
{categ:'Move', value:'Terrain Pulse'},
{categ:'Move', value:'Salt Cure'},
{categ:'Move', value:'Armor Cannon'},
{categ:'Move', value:'Bitter Blade'},
{categ:'Move', value:'Doodle'},
{categ:'Move', value:'Spicy Extract'},
{categ:'Move', value:'Lumina Crash'},
{categ:'Move', value:'Gigaton Hammer'},
{categ:'Move', value:'Triple Dive'},
{categ:'Move', value:'Flip Turn'},
{categ:'Move', value:'Jet Punch'},
{categ:'Move', value:'Spin Out'},
{categ:'Move', value:'Mortal Spin'},
{categ:'Move', value:'Last Respects'},
{categ:'Move', value:'Ice Spinner'},
{categ:'Move', value:'Fillet Away'},
{categ:'Move', value:'Order Up'},
{categ:'Move', value:'Kowtow Cleave'},
{categ:'Move', value:'Steel Roller'},
{categ:'Move', value:'Glaive Rush'},
{categ:'Move', value:'Make It Rain'},
{categ:'Move', value:'Ruination'},
{categ:'Move', value:'Scale Shot'},
{categ:'Move', value:'Collision Course'},
{categ:'Move', value:'Electro Drift'},
{categ:'Move', value:'Hydro Steam'},
{categ:'Move', value:'Psyblade'},
{categ:'Move', value:'Dragon Cheer'},
{categ:'Move', value:'Syrup Bomb'},
{categ:'Move', value:'Matcha Gotcha'},
{categ:'Move', value:'Ivy Cudgel'},
{categ:'Move', value:'Electro Shot'},
{categ:'Move', value:'Fickle Beam'},
{categ:'Move', value:'Burning Bulwark'},
{categ:'Move', value:'Thunderclap'},
{categ:'Move', value:'Dragon Hammer'},
{categ:'Move', value:'Rising Voltage'},
{categ:'Move', value:'Mighty Cleave'},
{categ:'Move', value:'Tachyon Cutter'},
{categ:'Move', value:'Tera Starstorm'},
{categ:'Move', value:'Malignant Chain'},
{categ:'Move', value:'Shadow Bone'},
{categ:'Move', value:'Light Of Ruin'},
{categ:'Move', value:'Shell Side Arm'},
{categ:'Move', value:'Strange Steam'},
{categ:'Move', value:'Freezing Glare'},
{categ:'Move', value:'Thunderous Kick'},
{categ:'Move', value:'Fiery Wrath'},
{categ:'Move', value:'Eerie Spell'},
{categ:'Move', value:'Snap Trap'},
{categ:'Move', value:'Chloroblast'},
{categ:'Move', value:'Infernal Parade'},
{categ:'Move', value:'Ceaseless Edge'},
{categ:'Move', value:'Victory Dance'},
{categ:'Move', value:'Bitter Malice'},
{categ:'Move', value:'Esper Wing'},
{categ:'Move', value:'Shelter'},
{categ:'Move', value:'Mountain Gale'},
{categ:'Move', value:'Triple Arrows'},
{categ:'Move', value:'Blood Moon'},
{categ:'Move', value:'Noxious Torque'},
{categ:'Move', value:'Floaty Fall'},
{categ:'Move', value:'Triple Axel'},
{categ:'Move', value:'Heart Stamp'},
{categ:'Move', value:'Surging Strikes'},
{categ:'Move', value:'Combat Torque'},
{categ:'Move', value:'Volt Tackle'},
{categ:'Move', value:'Magical Torque'},
{categ:'Move', value:'Trailblaze'},
{categ:'Move', value:'Glacial Lance'},
{categ:'Move', value:'Supercell Slam'},
{categ:'Move', value:'Wicked Torque'},
{categ:'Move', value:'Astral Barrage'},
{categ:'Move', value:'Scorching Sands'},
{categ:'Move', value:'Splishy Splash'},
{categ:'Move', value:'Blazing Torque'},
{categ:'Move', value:'Alluring Voice'},
{categ:'Move', value:'Behemoth Bash'},
{categ:'Move', value:'Behemoth Blade'},
{categ:'Move', value:'Grassy Glide'},
{categ:'Move', value:'Psychic Noise'},
{categ:'Move', value:'Steel Beam'},
{categ:'Move', value:'Happy Hour'},
{categ:'Move', value:'Secret Power'},
{categ:'Move', value:'Blast Burn'},
{categ:'Move', value:'Hydro Cannon'},
{categ:'Move', value:'Frenzy Plant'},
{categ:'Move', value:'Draco Meteor'},
{categ:'Move', value:'Sky Drop'},
{categ:'Move', value:'Water Pledge'},
{categ:'Move', value:'Fire Pledge'},
{categ:'Move', value:'Grass Pledge'},
{categ:'Move', value:'Meteor Beam'},
{categ:'Move', value:'Misty Explosion'},
{categ:'Move', value:'Burning Jealousy'},
{categ:'Move', value:'Lash Out'},
{categ:'Move', value:'Poltergeist'},
{categ:'Move', value:'Corrosive Gas'},
{categ:'Move', value:'Coaching'},
{categ:'Move', value:'Tera Blast'},
{categ:'Move', value:'Pounce'},
{categ:'Move', value:'Chilling Water'},
{categ:'Move', value:'Hard Press'},
{categ:'Move', value:'Temper Flare'},
{categ:'Move', value:'Upper Hand'},
{categ:'Move', value:'Freeze Shock'},
{categ:'Move', value:'Ice Burn'},
{categ:'Move', value:'Hyperspace Fury'},
{categ:'Move', value:'Eternabeam'},
];
